# Generated by Django 3.2.3 on 2021-06-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='imagem',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='autor',
            name='pais_origem',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='autor',
            name='url_wiki',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
