# Generated by Django 3.2.3 on 2021-07-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_alter_perfil_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='url_foto',
            field=models.CharField(blank=True, default=None, max_length=300),
        ),
    ]
