# Generated by Django 3.2.3 on 2021-07-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_alter_perfil_url_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='url_foto',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
