# Generated by Django 3.2.3 on 2021-07-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_alter_perfil_url_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='url_foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/%Y%m/'),
        ),
    ]
