# Generated by Django 3.2.3 on 2021-06-06 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editoras', '0001_initial'),
        ('livros', '0002_auto_20210606_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='editoras.editora'),
        ),
    ]
