# Generated by Django 3.2.3 on 2021-06-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_livro_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='link_amazon',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='livro',
            name='sinopse',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
